
["General Options"]
	#Set this value to 'true' whenever you want the default restrictions to be regenerated. [true/false]
	generate_defaults = false
	#List all the stages that you want to have.
	stages = ["A1", "Twilight_Forest", "L1", "A2", "L2", "Nether", "A3", "A4", "A5", "Otherside", "End", "A6", "A7"]
	#Set this value to 'true' whenever you're having issues, this will allow the mod to output everything it tries to do in the log.
	debugMode = false

